# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ApplicationType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ApplicationType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15\x41pplicationType.proto\x12\x05\x62link*T\n\x0f\x41pplicationType\x12\x15\n\x11\x45N_APP_TYPE_BLINK\x10\x01\x12\x14\n\x10\x45N_APP_TYPE_BLUE\x10\x02\x12\x14\n\x10\x45N_APP_TYPE_PINK\x10\x03\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_APPLICATIONTYPE = _descriptor.EnumDescriptor(
  name='ApplicationType',
  full_name='blink.ApplicationType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_APP_TYPE_BLINK', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_APP_TYPE_BLUE', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_APP_TYPE_PINK', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=116,
)
_sym_db.RegisterEnumDescriptor(_APPLICATIONTYPE)

ApplicationType = enum_type_wrapper.EnumTypeWrapper(_APPLICATIONTYPE)
EN_APP_TYPE_BLINK = 1
EN_APP_TYPE_BLUE = 2
EN_APP_TYPE_PINK = 3


DESCRIPTOR.enum_types_by_name['ApplicationType'] = _APPLICATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
