# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BusinessType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='BusinessType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12\x42usinessType.proto\x12\x05\x62link*B\n\x0c\x42usinessType\x12\x17\n\x13\x45N_BUSINESS_TYPE_IM\x10\x01\x12\x19\n\x15\x45N_BUSINESS_TYPE_LIVE\x10\x02\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_BUSINESSTYPE = _descriptor.EnumDescriptor(
  name='BusinessType',
  full_name='blink.BusinessType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_BUSINESS_TYPE_IM', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_BUSINESS_TYPE_LIVE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=29,
  serialized_end=95,
)
_sym_db.RegisterEnumDescriptor(_BUSINESSTYPE)

BusinessType = enum_type_wrapper.EnumTypeWrapper(_BUSINESSTYPE)
EN_BUSINESS_TYPE_IM = 1
EN_BUSINESS_TYPE_LIVE = 2


DESCRIPTOR.enum_types_by_name['BusinessType'] = _BUSINESSTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
