# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CallerProfileContext.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CallerProfileContext.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x1a\x43\x61llerProfileContext.proto\x12\x05\x62link\"&\n\x14\x43\x61llerProfileContext\x12\x0e\n\x06\x63\x61ller\x18\x01 \x02(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_CALLERPROFILECONTEXT = _descriptor.Descriptor(
  name='CallerProfileContext',
  full_name='blink.CallerProfileContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caller', full_name='blink.CallerProfileContext.caller', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=75,
)

DESCRIPTOR.message_types_by_name['CallerProfileContext'] = _CALLERPROFILECONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CallerProfileContext = _reflection.GeneratedProtocolMessageType('CallerProfileContext', (_message.Message,), {
  'DESCRIPTOR' : _CALLERPROFILECONTEXT,
  '__module__' : 'CallerProfileContext_pb2'
  # @@protoc_insertion_point(class_scope:blink.CallerProfileContext)
  })
_sym_db.RegisterMessage(CallerProfileContext)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
