# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContentType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContentType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x11\x43ontentType.proto\x12\x05\x62link*a\n\x0b\x43ontentType\x12\x1f\n\x1b\x43ONTENT_TYPE_FORM_URLENCODE\x10\x01\x12\x1a\n\x16\x43ONTENT_TYPE_FORM_DATA\x10\x02\x12\x15\n\x11\x43ONTENT_TYPE_JSON\x10\x03\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_CONTENTTYPE = _descriptor.EnumDescriptor(
  name='ContentType',
  full_name='blink.ContentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CONTENT_TYPE_FORM_URLENCODE', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTENT_TYPE_FORM_DATA', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CONTENT_TYPE_JSON', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=28,
  serialized_end=125,
)
_sym_db.RegisterEnumDescriptor(_CONTENTTYPE)

ContentType = enum_type_wrapper.EnumTypeWrapper(_CONTENTTYPE)
CONTENT_TYPE_FORM_URLENCODE = 1
CONTENT_TYPE_FORM_DATA = 2
CONTENT_TYPE_JSON = 3


DESCRIPTOR.enum_types_by_name['ContentType'] = _CONTENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
