# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DbGroupSessions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DbGroupSession_pb2 as DbGroupSession__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='DbGroupSessions.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15\x44\x62GroupSessions.proto\x12\x05\x62link\x1a\x14\x44\x62GroupSession.proto\"@\n\x0f\x44\x62GroupSessions\x12-\n\x0egroup_sessions\x18\x01 \x03(\x0b\x32\x15.blink.DbGroupSessionB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[DbGroupSession__pb2.DESCRIPTOR,])




_DBGROUPSESSIONS = _descriptor.Descriptor(
  name='DbGroupSessions',
  full_name='blink.DbGroupSessions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_sessions', full_name='blink.DbGroupSessions.group_sessions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=118,
)

_DBGROUPSESSIONS.fields_by_name['group_sessions'].message_type = DbGroupSession__pb2._DBGROUPSESSION
DESCRIPTOR.message_types_by_name['DbGroupSessions'] = _DBGROUPSESSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbGroupSessions = _reflection.GeneratedProtocolMessageType('DbGroupSessions', (_message.Message,), {
  'DESCRIPTOR' : _DBGROUPSESSIONS,
  '__module__' : 'DbGroupSessions_pb2'
  # @@protoc_insertion_point(class_scope:blink.DbGroupSessions)
  })
_sym_db.RegisterMessage(DbGroupSessions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
