# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DbGroupSession.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DbGroupSession.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14\x44\x62GroupSession.proto\x12\x05\x62link\"\xb5\x02\n\x0e\x44\x62GroupSession\x12\x12\n\nack_cursor\x18\x05 \x01(\x04\x12\x11\n\tack_seqno\x18\x04 \x01(\x04\x12\x10\n\x08\x61t_seqno\x18\x07 \x01(\x04\x12\x15\n\rdeleted_seqno\x18\x08 \x01(\x04\x12\x17\n\x0f\x64raw_back_count\x18\x06 \x01(\x04\x12\x13\n\x0bgroup_cover\x18\n \x01(\t\x12\x10\n\x08group_id\x18\x01 \x01(\x04\x12\x12\n\ngroup_name\x18\x0b \x01(\t\x12\x12\n\ngroup_type\x18\x0f \x01(\r\x12\x0e\n\x06is_dnd\x18\x0e \x01(\r\x12\x11\n\tmax_seqno\x18\r \x01(\x04\x12\x14\n\x0creceiver_uid\x18\x02 \x01(\x04\x12\x12\n\nsession_ts\x18\x0c \x01(\x04\x12\x0e\n\x06status\x18\t \x01(\r\x12\x0e\n\x06top_ts\x18\x03 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_DBGROUPSESSION = _descriptor.Descriptor(
  name='DbGroupSession',
  full_name='blink.DbGroupSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack_cursor', full_name='blink.DbGroupSession.ack_cursor', index=0,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack_seqno', full_name='blink.DbGroupSession.ack_seqno', index=1,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='at_seqno', full_name='blink.DbGroupSession.at_seqno', index=2,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_seqno', full_name='blink.DbGroupSession.deleted_seqno', index=3,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='draw_back_count', full_name='blink.DbGroupSession.draw_back_count', index=4,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_cover', full_name='blink.DbGroupSession.group_cover', index=5,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='blink.DbGroupSession.group_id', index=6,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='blink.DbGroupSession.group_name', index=7,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_type', full_name='blink.DbGroupSession.group_type', index=8,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_dnd', full_name='blink.DbGroupSession.is_dnd', index=9,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_seqno', full_name='blink.DbGroupSession.max_seqno', index=10,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_uid', full_name='blink.DbGroupSession.receiver_uid', index=11,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_ts', full_name='blink.DbGroupSession.session_ts', index=12,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='blink.DbGroupSession.status', index=13,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_ts', full_name='blink.DbGroupSession.top_ts', index=14,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=341,
)

DESCRIPTOR.message_types_by_name['DbGroupSession'] = _DBGROUPSESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbGroupSession = _reflection.GeneratedProtocolMessageType('DbGroupSession', (_message.Message,), {
  'DESCRIPTOR' : _DBGROUPSESSION,
  '__module__' : 'DbGroupSession_pb2'
  # @@protoc_insertion_point(class_scope:blink.DbGroupSession)
  })
_sym_db.RegisterMessage(DbGroupSession)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
