# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DbSingleSession.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DbSingleSession.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15\x44\x62SingleSession.proto\x12\x05\x62link\"\x8c\x02\n\x0f\x44\x62SingleSession\x12\x12\n\nack_cursor\x18\x06 \x01(\x04\x12\x11\n\tack_seqno\x18\x05 \x01(\x04\x12\x15\n\rdeleted_seqno\x18\x07 \x01(\x04\x12\x17\n\x0f\x64raw_back_count\x18\x0b \x01(\r\x12\x0e\n\x06is_dnd\x18\n \x01(\r\x12\x11\n\tis_follow\x18\t \x01(\r\x12\x11\n\tmax_seqno\x18\x04 \x01(\x04\x12\x14\n\x0creceiver_uid\x18\x02 \x01(\x04\x12\x12\n\nsender_uid\x18\x01 \x01(\x04\x12\x12\n\nsession_ts\x18\x03 \x01(\x04\x12\x0e\n\x06status\x18\r \x01(\r\x12\x0e\n\x06top_ts\x18\x08 \x01(\x04\x12\x0e\n\x06unread\x18\x0c \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_DBSINGLESESSION = _descriptor.Descriptor(
  name='DbSingleSession',
  full_name='blink.DbSingleSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack_cursor', full_name='blink.DbSingleSession.ack_cursor', index=0,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ack_seqno', full_name='blink.DbSingleSession.ack_seqno', index=1,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deleted_seqno', full_name='blink.DbSingleSession.deleted_seqno', index=2,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='draw_back_count', full_name='blink.DbSingleSession.draw_back_count', index=3,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_dnd', full_name='blink.DbSingleSession.is_dnd', index=4,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_follow', full_name='blink.DbSingleSession.is_follow', index=5,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_seqno', full_name='blink.DbSingleSession.max_seqno', index=6,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_uid', full_name='blink.DbSingleSession.receiver_uid', index=7,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_uid', full_name='blink.DbSingleSession.sender_uid', index=8,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_ts', full_name='blink.DbSingleSession.session_ts', index=9,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='blink.DbSingleSession.status', index=10,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='top_ts', full_name='blink.DbSingleSession.top_ts', index=11,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unread', full_name='blink.DbSingleSession.unread', index=12,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=301,
)

DESCRIPTOR.message_types_by_name['DbSingleSession'] = _DBSINGLESESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DbSingleSession = _reflection.GeneratedProtocolMessageType('DbSingleSession', (_message.Message,), {
  'DESCRIPTOR' : _DBSINGLESESSION,
  '__module__' : 'DbSingleSession_pb2'
  # @@protoc_insertion_point(class_scope:blink.DbSingleSession)
  })
_sym_db.RegisterMessage(DbSingleSession)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
