# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DeviceType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DeviceType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10\x44\x65viceType.proto\x12\x05\x62link*w\n\nDeviceType\x12\x13\n\x0f\x45N_DEV_TYPE_IOS\x10\x01\x12\x17\n\x13\x45N_DEV_TYPE_ANDROID\x10\x02\x12\x12\n\x0e\x45N_DEV_TYPE_H5\x10\x03\x12\x12\n\x0e\x45N_DEV_TYPE_PC\x10\x04\x12\x13\n\x0f\x45N_DEV_TYPE_WEB\x10\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_DEVICETYPE = _descriptor.EnumDescriptor(
  name='DeviceType',
  full_name='blink.DeviceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_DEV_TYPE_IOS', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_DEV_TYPE_ANDROID', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_DEV_TYPE_H5', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_DEV_TYPE_PC', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_DEV_TYPE_WEB', index=4, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=27,
  serialized_end=146,
)
_sym_db.RegisterEnumDescriptor(_DEVICETYPE)

DeviceType = enum_type_wrapper.EnumTypeWrapper(_DEVICETYPE)
EN_DEV_TYPE_IOS = 1
EN_DEV_TYPE_ANDROID = 2
EN_DEV_TYPE_H5 = 3
EN_DEV_TYPE_PC = 4
EN_DEV_TYPE_WEB = 5


DESCRIPTOR.enum_types_by_name['DeviceType'] = _DEVICETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
