# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DummyRsp.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DummyRsp.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0e\x44ummyRsp.proto\x12\x05\x62link\"\x1b\n\x08\x44ummyRsp\x12\x0f\n\x07__blank\x18\x01 \x03(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_DUMMYRSP = _descriptor.Descriptor(
  name='DummyRsp',
  full_name='blink.DummyRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='__blank', full_name='blink.DummyRsp.__blank', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['DummyRsp'] = _DUMMYRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DummyRsp = _reflection.GeneratedProtocolMessageType('DummyRsp', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYRSP,
  '__module__' : 'DummyRsp_pb2'
  # @@protoc_insertion_point(class_scope:blink.DummyRsp)
  })
_sym_db.RegisterMessage(DummyRsp)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
