# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DummyReq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DummyReq.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0e\x44ummyReq.proto\x12\x05\x62link\"\n\n\x08\x44ummyReqB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_DUMMYREQ = _descriptor.Descriptor(
  name='DummyReq',
  full_name='blink.DummyReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=35,
)

DESCRIPTOR.message_types_by_name['DummyReq'] = _DUMMYREQ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DummyReq = _reflection.GeneratedProtocolMessageType('DummyReq', (_message.Message,), {
  'DESCRIPTOR' : _DUMMYREQ,
  '__module__' : 'DummyReq_pb2'
  # @@protoc_insertion_point(class_scope:blink.DummyReq)
  })
_sym_db.RegisterMessage(DummyReq)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
