# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FriendRelation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FriendRelation.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14\x46riendRelation.proto\x12\x05\x62link\"Q\n\x0e\x46riendRelation\x12\x0c\n\x04\x66\x61\x63\x65\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x11\n\tvip_level\x18\x04 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_FRIENDRELATION = _descriptor.Descriptor(
  name='FriendRelation',
  full_name='blink.FriendRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='face', full_name='blink.FriendRelation.face', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.FriendRelation.uid', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='blink.FriendRelation.user_name', index=2,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vip_level', full_name='blink.FriendRelation.vip_level', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['FriendRelation'] = _FRIENDRELATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FriendRelation = _reflection.GeneratedProtocolMessageType('FriendRelation', (_message.Message,), {
  'DESCRIPTOR' : _FRIENDRELATION,
  '__module__' : 'FriendRelation_pb2'
  # @@protoc_insertion_point(class_scope:blink.FriendRelation)
  })
_sym_db.RegisterMessage(FriendRelation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
