# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupRelation.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GroupRelation.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x13GroupRelation.proto\x12\x05\x62link\"\xeb\x01\n\rGroupRelation\x12\x17\n\x0f\x66\x61ns_medal_name\x18\n \x01(\t\x12\x13\n\x0bgroup_cover\x18\x05 \x01(\t\x12\x10\n\x08group_id\x18\x01 \x02(\x04\x12\x13\n\x0bgroup_level\x18\x04 \x01(\r\x12\x12\n\ngroup_name\x18\x06 \x01(\t\x12\x14\n\x0cgroup_notice\x18\x07 \x01(\t\x12\x12\n\ngroup_type\x18\x03 \x01(\r\x12\x13\n\x0bmember_role\x18\t \x01(\x05\x12\x11\n\towner_uid\x18\x02 \x01(\x04\x12\x0f\n\x07room_id\x18\x0b \x01(\x04\x12\x0e\n\x06status\x18\x08 \x01(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_GROUPRELATION = _descriptor.Descriptor(
  name='GroupRelation',
  full_name='blink.GroupRelation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fans_medal_name', full_name='blink.GroupRelation.fans_medal_name', index=0,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_cover', full_name='blink.GroupRelation.group_cover', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='blink.GroupRelation.group_id', index=2,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_level', full_name='blink.GroupRelation.group_level', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='blink.GroupRelation.group_name', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_notice', full_name='blink.GroupRelation.group_notice', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_type', full_name='blink.GroupRelation.group_type', index=6,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='member_role', full_name='blink.GroupRelation.member_role', index=7,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='owner_uid', full_name='blink.GroupRelation.owner_uid', index=8,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='room_id', full_name='blink.GroupRelation.room_id', index=9,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='blink.GroupRelation.status', index=10,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=266,
)

DESCRIPTOR.message_types_by_name['GroupRelation'] = _GROUPRELATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroupRelation = _reflection.GeneratedProtocolMessageType('GroupRelation', (_message.Message,), {
  'DESCRIPTOR' : _GROUPRELATION,
  '__module__' : 'GroupRelation_pb2'
  # @@protoc_insertion_point(class_scope:blink.GroupRelation)
  })
_sym_db.RegisterMessage(GroupRelation)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
