# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GroupDesc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GroupDesc.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0fGroupDesc.proto\x12\x05\x62link\"s\n\tGroupDesc\x12\x17\n\x0f\x66\x61ns_medal_name\x18\x05 \x01(\t\x12\x13\n\x0bgroup_cover\x18\x03 \x01(\t\x12\x10\n\x08group_id\x18\x01 \x02(\x04\x12\x12\n\ngroup_name\x18\x02 \x01(\t\x12\x12\n\ngroup_type\x18\x04 \x01(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_GROUPDESC = _descriptor.Descriptor(
  name='GroupDesc',
  full_name='blink.GroupDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fans_medal_name', full_name='blink.GroupDesc.fans_medal_name', index=0,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_cover', full_name='blink.GroupDesc.group_cover', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_id', full_name='blink.GroupDesc.group_id', index=2,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_name', full_name='blink.GroupDesc.group_name', index=3,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_type', full_name='blink.GroupDesc.group_type', index=4,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['GroupDesc'] = _GROUPDESC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GroupDesc = _reflection.GeneratedProtocolMessageType('GroupDesc', (_message.Message,), {
  'DESCRIPTOR' : _GROUPDESC,
  '__module__' : 'GroupDesc_pb2'
  # @@protoc_insertion_point(class_scope:blink.GroupDesc)
  })
_sym_db.RegisterMessage(GroupDesc)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
