# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HttpMethod.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='HttpMethod.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10HttpMethod.proto\x12\x05\x62link*\x8b\x01\n\nHttpMethod\x12\x0c\n\x08HTTP_GET\x10\x01\x12\r\n\tHTTP_POST\x10\x02\x12\r\n\tHTTP_HEAD\x10\x03\x12\x10\n\x0cHTTP_OPTIONS\x10\x04\x12\x0c\n\x08HTTP_PUT\x10\x05\x12\x0f\n\x0bHTTP_DELETE\x10\x06\x12\x0e\n\nHTTP_TRACE\x10\x07\x12\x10\n\x0cHTTP_CONNECT\x10\x08\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_HTTPMETHOD = _descriptor.EnumDescriptor(
  name='HttpMethod',
  full_name='blink.HttpMethod',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='HTTP_GET', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_POST', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_HEAD', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_OPTIONS', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_PUT', index=4, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_DELETE', index=5, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_TRACE', index=6, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HTTP_CONNECT', index=7, number=8,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=28,
  serialized_end=167,
)
_sym_db.RegisterEnumDescriptor(_HTTPMETHOD)

HttpMethod = enum_type_wrapper.EnumTypeWrapper(_HTTPMETHOD)
HTTP_GET = 1
HTTP_POST = 2
HTTP_HEAD = 3
HTTP_OPTIONS = 4
HTTP_PUT = 5
HTTP_DELETE = 6
HTTP_TRACE = 7
HTTP_CONNECT = 8


DESCRIPTOR.enum_types_by_name['HttpMethod'] = _HTTPMETHOD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
