# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LastMsgKey.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Msg_pb2 as Msg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='LastMsgKey.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10LastMsgKey.proto\x12\x05\x62link\x1a\tMsg.proto\"`\n\nLastMsgKey\x12\x17\n\x03msg\x18\x04 \x01(\x0b\x32\n.blink.Msg\x12\x0f\n\x07msg_key\x18\x03 \x01(\x04\x12\x14\n\x0creceiver_uid\x18\x01 \x02(\x04\x12\x12\n\nsession_id\x18\x02 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Msg__pb2.DESCRIPTOR,])




_LASTMSGKEY = _descriptor.Descriptor(
  name='LastMsgKey',
  full_name='blink.LastMsgKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='blink.LastMsgKey.msg', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_key', full_name='blink.LastMsgKey.msg_key', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_uid', full_name='blink.LastMsgKey.receiver_uid', index=2,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_id', full_name='blink.LastMsgKey.session_id', index=3,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=134,
)

_LASTMSGKEY.fields_by_name['msg'].message_type = Msg__pb2._MSG
DESCRIPTOR.message_types_by_name['LastMsgKey'] = _LASTMSGKEY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LastMsgKey = _reflection.GeneratedProtocolMessageType('LastMsgKey', (_message.Message,), {
  'DESCRIPTOR' : _LASTMSGKEY,
  '__module__' : 'LastMsgKey_pb2'
  # @@protoc_insertion_point(class_scope:blink.LastMsgKey)
  })
_sym_db.RegisterMessage(LastMsgKey)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
