# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MonitorDataInner.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MonitorDataInner.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16MonitorDataInner.proto\x12\x05\x62link\"g\n\x10MonitorDataInner\x12\x13\n\x0bmonitor_key\x18\x02 \x02(\t\x12\x15\n\rmonitor_value\x18\x03 \x02(\x05\x12\x14\n\x0cservice_type\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_MONITORDATAINNER = _descriptor.Descriptor(
  name='MonitorDataInner',
  full_name='blink.MonitorDataInner',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='monitor_key', full_name='blink.MonitorDataInner.monitor_key', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='monitor_value', full_name='blink.MonitorDataInner.monitor_value', index=1,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_type', full_name='blink.MonitorDataInner.service_type', index=2,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='blink.MonitorDataInner.timestamp', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=136,
)

DESCRIPTOR.message_types_by_name['MonitorDataInner'] = _MONITORDATAINNER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonitorDataInner = _reflection.GeneratedProtocolMessageType('MonitorDataInner', (_message.Message,), {
  'DESCRIPTOR' : _MONITORDATAINNER,
  '__module__' : 'MonitorDataInner_pb2'
  # @@protoc_insertion_point(class_scope:blink.MonitorDataInner)
  })
_sym_db.RegisterMessage(MonitorDataInner)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
