# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgBody.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import UserContext_pb2 as UserContext__pb2
from . import ProfileContexts_pb2 as ProfileContexts__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MsgBody.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\rMsgBody.proto\x12\x05\x62link\x1a\x11UserContext.proto\x1a\x15ProfileContexts.proto\"\xd9\x02\n\x07MsgBody\x12\r\n\x05\x62uild\x18\x10 \x01(\r\x12\x11\n\tcall_type\x18\x03 \x01(\x05\x12\x12\n\ncli_req_id\x18\x02 \x01(\x04\x12\x0b\n\x03\x63md\x18\x01 \x01(\x05\x12\x11\n\tcpu_usage\x18\r \x01(\x05\x12\x10\n\x08\x65rr_code\x18\t \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x0b \x01(\t\x12\x0e\n\x06method\x18\x08 \x01(\x05\x12\x10\n\x08mobi_app\x18\x0f \x01(\t\x12\x18\n\x10need_trace_point\x18\x0c \x01(\x05\x12\x0f\n\x07payload\x18\n \x01(\x0c\x12,\n\x0cprofile_ctxs\x18\x0e \x01(\x0b\x32\x16.blink.ProfileContexts\x12\x0f\n\x07service\x18\x07 \x01(\t\x12\x14\n\x0csession_code\x18\x04 \x01(\x04\x12\x11\n\tss_req_id\x18\x06 \x01(\x04\x12 \n\x04uctx\x18\x05 \x01(\x0b\x32\x12.blink.UserContext2?\n\x0eMsgBodyService\x12-\n\x0bSendMsgBody\x12\x0e.blink.MsgBody\x1a\x0e.blink.MsgBodyB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[UserContext__pb2.DESCRIPTOR,ProfileContexts__pb2.DESCRIPTOR,])




_MSGBODY = _descriptor.Descriptor(
  name='MsgBody',
  full_name='blink.MsgBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='build', full_name='blink.MsgBody.build', index=0,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='call_type', full_name='blink.MsgBody.call_type', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cli_req_id', full_name='blink.MsgBody.cli_req_id', index=2,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='blink.MsgBody.cmd', index=3,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='blink.MsgBody.cpu_usage', index=4,
      number=13, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='blink.MsgBody.err_code', index=5,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='blink.MsgBody.err_msg', index=6,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='blink.MsgBody.method', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mobi_app', full_name='blink.MsgBody.mobi_app', index=8,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='need_trace_point', full_name='blink.MsgBody.need_trace_point', index=9,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='blink.MsgBody.payload', index=10,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profile_ctxs', full_name='blink.MsgBody.profile_ctxs', index=11,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='blink.MsgBody.service', index=12,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_code', full_name='blink.MsgBody.session_code', index=13,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ss_req_id', full_name='blink.MsgBody.ss_req_id', index=14,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uctx', full_name='blink.MsgBody.uctx', index=15,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=412,
)

_MSGBODY.fields_by_name['profile_ctxs'].message_type = ProfileContexts__pb2._PROFILECONTEXTS
_MSGBODY.fields_by_name['uctx'].message_type = UserContext__pb2._USERCONTEXT
DESCRIPTOR.message_types_by_name['MsgBody'] = _MSGBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgBody = _reflection.GeneratedProtocolMessageType('MsgBody', (_message.Message,), {
  'DESCRIPTOR' : _MSGBODY,
  '__module__' : 'MsgBody_pb2'
  # @@protoc_insertion_point(class_scope:blink.MsgBody)
  })
_sym_db.RegisterMessage(MsgBody)


DESCRIPTOR._options = None

_MSGBODYSERVICE = _descriptor.ServiceDescriptor(
  name='MsgBodyService',
  full_name='blink.MsgBodyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=414,
  serialized_end=477,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMsgBody',
    full_name='blink.MsgBodyService.SendMsgBody',
    index=0,
    containing_service=None,
    input_type=_MSGBODY,
    output_type=_MSGBODY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MSGBODYSERVICE)

DESCRIPTOR.services_by_name['MsgBodyService'] = _MSGBODYSERVICE

# @@protoc_insertion_point(module_scope)
