# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MsgHead.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MsgHead.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\rMsgHead.proto\x12\x05\x62link\"#\n\x07MsgHead\x12\x0b\n\x03\x63rc\x18\x02 \x02(\x07\x12\x0b\n\x03len\x18\x01 \x02(\x07\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_MSGHEAD = _descriptor.Descriptor(
  name='MsgHead',
  full_name='blink.MsgHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='crc', full_name='blink.MsgHead.crc', index=0,
      number=2, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='len', full_name='blink.MsgHead.len', index=1,
      number=1, type=7, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['MsgHead'] = _MSGHEAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MsgHead = _reflection.GeneratedProtocolMessageType('MsgHead', (_message.Message,), {
  'DESCRIPTOR' : _MSGHEAD,
  '__module__' : 'MsgHead_pb2'
  # @@protoc_insertion_point(class_scope:blink.MsgHead)
  })
_sym_db.RegisterMessage(MsgHead)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
