# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MssItem.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MssItem.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\rMssItem.proto\x12\x05\x62link\"B\n\x07MssItem\x12\x0e\n\x06peerid\x18\x01 \x01(\x04\x12\r\n\x05seqno\x18\x03 \x01(\x04\x12\n\n\x02ts\x18\x04 \x01(\x04\x12\x0c\n\x04type\x18\x02 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_MSSITEM = _descriptor.Descriptor(
  name='MssItem',
  full_name='blink.MssItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peerid', full_name='blink.MssItem.peerid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqno', full_name='blink.MssItem.seqno', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='blink.MssItem.ts', index=2,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='blink.MssItem.type', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=90,
)

DESCRIPTOR.message_types_by_name['MssItem'] = _MSSITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MssItem = _reflection.GeneratedProtocolMessageType('MssItem', (_message.Message,), {
  'DESCRIPTOR' : _MSSITEM,
  '__module__' : 'MssItem_pb2'
  # @@protoc_insertion_point(class_scope:blink.MssItem)
  })
_sym_db.RegisterMessage(MssItem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
