# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NotifyInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='NotifyInfo.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10NotifyInfo.proto\x12\x05\x62link\"G\n\nNotifyInfo\x12\x10\n\x08msg_type\x18\x01 \x01(\r\x12\x14\n\x0csession_type\x18\x03 \x01(\r\x12\x11\n\ttalker_id\x18\x02 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_NOTIFYINFO = _descriptor.Descriptor(
  name='NotifyInfo',
  full_name='blink.NotifyInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='blink.NotifyInfo.msg_type', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_type', full_name='blink.NotifyInfo.session_type', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='talker_id', full_name='blink.NotifyInfo.talker_id', index=2,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['NotifyInfo'] = _NOTIFYINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NotifyInfo = _reflection.GeneratedProtocolMessageType('NotifyInfo', (_message.Message,), {
  'DESCRIPTOR' : _NOTIFYINFO,
  '__module__' : 'NotifyInfo_pb2'
  # @@protoc_insertion_point(class_scope:blink.NotifyInfo)
  })
_sym_db.RegisterMessage(NotifyInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
