# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RebuildCacheCb.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RebuildCacheCb.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14RebuildCacheCb.proto\x12\x05\x62link\"I\n\x0eRebuildCacheCb\x12\x14\n\x0crebuild_type\x18\x03 \x01(\r\x12\x14\n\x0csession_type\x18\x02 \x01(\r\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REBUILDCACHECB = _descriptor.Descriptor(
  name='RebuildCacheCb',
  full_name='blink.RebuildCacheCb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rebuild_type', full_name='blink.RebuildCacheCb.rebuild_type', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_type', full_name='blink.RebuildCacheCb.session_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.RebuildCacheCb.uid', index=2,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=104,
)

DESCRIPTOR.message_types_by_name['RebuildCacheCb'] = _REBUILDCACHECB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RebuildCacheCb = _reflection.GeneratedProtocolMessageType('RebuildCacheCb', (_message.Message,), {
  'DESCRIPTOR' : _REBUILDCACHECB,
  '__module__' : 'RebuildCacheCb_pb2'
  # @@protoc_insertion_point(class_scope:blink.RebuildCacheCb)
  })
_sym_db.RegisterMessage(RebuildCacheCb)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
