# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RecverType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RecverType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10RecverType.proto\x12\x05\x62link*Y\n\nRecverType\x12\x17\n\x13\x45N_RECVER_TYPE_PEER\x10\x01\x12\x18\n\x14\x45N_RECVER_TYPE_GROUP\x10\x02\x12\x18\n\x14\x45N_RECVER_TYPE_PEERS\x10\x03\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_RECVERTYPE = _descriptor.EnumDescriptor(
  name='RecverType',
  full_name='blink.RecverType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_RECVER_TYPE_PEER', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_RECVER_TYPE_GROUP', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_RECVER_TYPE_PEERS', index=2, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=27,
  serialized_end=116,
)
_sym_db.RegisterEnumDescriptor(_RECVERTYPE)

RecverType = enum_type_wrapper.EnumTypeWrapper(_RECVERTYPE)
EN_RECVER_TYPE_PEER = 1
EN_RECVER_TYPE_GROUP = 2
EN_RECVER_TYPE_PEERS = 3


DESCRIPTOR.enum_types_by_name['RecverType'] = _RECVERTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
