# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelationLogType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RelationLogType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15RelationLogType.proto\x12\x05\x62link*y\n\x0fRelationLogType\x12\x17\n\x13\x45N_INVALID_LOG_TYPE\x10\x00\x12\x11\n\rEN_ADD_FRIEND\x10\x01\x12\x14\n\x10\x45N_REMOVE_FRIEND\x10\x02\x12\x11\n\rEN_JOIN_GROUP\x10\x03\x12\x11\n\rEN_EXIT_GROUP\x10\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_RELATIONLOGTYPE = _descriptor.EnumDescriptor(
  name='RelationLogType',
  full_name='blink.RelationLogType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_INVALID_LOG_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_ADD_FRIEND', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_REMOVE_FRIEND', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_JOIN_GROUP', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_EXIT_GROUP', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=32,
  serialized_end=153,
)
_sym_db.RegisterEnumDescriptor(_RELATIONLOGTYPE)

RelationLogType = enum_type_wrapper.EnumTypeWrapper(_RELATIONLOGTYPE)
EN_INVALID_LOG_TYPE = 0
EN_ADD_FRIEND = 1
EN_REMOVE_FRIEND = 2
EN_JOIN_GROUP = 3
EN_EXIT_GROUP = 4


DESCRIPTOR.enum_types_by_name['RelationLogType'] = _RELATIONLOGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
