# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RelationLog.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import GroupRelation_pb2 as GroupRelation__pb2
from . import FriendRelation_pb2 as FriendRelation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RelationLog.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x11RelationLog.proto\x12\x05\x62link\x1a\x13GroupRelation.proto\x1a\x14\x46riendRelation.proto\"\x92\x01\n\x0bRelationLog\x12.\n\x0f\x66riend_relation\x18\x03 \x01(\x0b\x32\x15.blink.FriendRelation\x12,\n\x0egroup_relation\x18\x04 \x01(\x0b\x32\x14.blink.GroupRelation\x12\x10\n\x08log_type\x18\x01 \x02(\x05\x12\x13\n\x0boplog_seqno\x18\x02 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[GroupRelation__pb2.DESCRIPTOR,FriendRelation__pb2.DESCRIPTOR,])




_RELATIONLOG = _descriptor.Descriptor(
  name='RelationLog',
  full_name='blink.RelationLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_relation', full_name='blink.RelationLog.friend_relation', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='group_relation', full_name='blink.RelationLog.group_relation', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='log_type', full_name='blink.RelationLog.log_type', index=2,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oplog_seqno', full_name='blink.RelationLog.oplog_seqno', index=3,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=218,
)

_RELATIONLOG.fields_by_name['friend_relation'].message_type = FriendRelation__pb2._FRIENDRELATION
_RELATIONLOG.fields_by_name['group_relation'].message_type = GroupRelation__pb2._GROUPRELATION
DESCRIPTOR.message_types_by_name['RelationLog'] = _RELATIONLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RelationLog = _reflection.GeneratedProtocolMessageType('RelationLog', (_message.Message,), {
  'DESCRIPTOR' : _RELATIONLOG,
  '__module__' : 'RelationLog_pb2'
  # @@protoc_insertion_point(class_scope:blink.RelationLog)
  })
_sym_db.RegisterMessage(RelationLog)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
