# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqAckSessions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqAckSessions.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14ReqAckSessions.proto\x12\x05\x62link\"@\n\x0eReqAckSessions\x12\x10\n\x08\x62\x65gin_ts\x18\x01 \x01(\x04\x12\x0e\n\x06\x65nd_ts\x18\x02 \x01(\r\x12\x0c\n\x04size\x18\x03 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQACKSESSIONS = _descriptor.Descriptor(
  name='ReqAckSessions',
  full_name='blink.ReqAckSessions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_ts', full_name='blink.ReqAckSessions.begin_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_ts', full_name='blink.ReqAckSessions.end_ts', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='blink.ReqAckSessions.size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['ReqAckSessions'] = _REQACKSESSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqAckSessions = _reflection.GeneratedProtocolMessageType('ReqAckSessions', (_message.Message,), {
  'DESCRIPTOR' : _REQACKSESSIONS,
  '__module__' : 'ReqAckSessions_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqAckSessions)
  })
_sym_db.RegisterMessage(ReqAckSessions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
