# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqAckAssisMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqAckAssisMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14ReqAckAssisMsg.proto\x12\x05\x62link\"#\n\x0eReqAckAssisMsg\x12\x11\n\tack_seqno\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQACKASSISMSG = _descriptor.Descriptor(
  name='ReqAckAssisMsg',
  full_name='blink.ReqAckAssisMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ack_seqno', full_name='blink.ReqAckAssisMsg.ack_seqno', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['ReqAckAssisMsg'] = _REQACKASSISMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqAckAssisMsg = _reflection.GeneratedProtocolMessageType('ReqAckAssisMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQACKASSISMSG,
  '__module__' : 'ReqAckAssisMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqAckAssisMsg)
  })
_sym_db.RegisterMessage(ReqAckAssisMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
