# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqBatRmSess.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqBatRmSess.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12ReqBatRmSess.proto\x12\x05\x62link\"\x0e\n\x0cReqBatRmSessB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQBATRMSESS = _descriptor.Descriptor(
  name='ReqBatRmSess',
  full_name='blink.ReqBatRmSess',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['ReqBatRmSess'] = _REQBATRMSESS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqBatRmSess = _reflection.GeneratedProtocolMessageType('ReqBatRmSess', (_message.Message,), {
  'DESCRIPTOR' : _REQBATRMSESS,
  '__module__' : 'ReqBatRmSess_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqBatRmSess)
  })
_sym_db.RegisterMessage(ReqBatRmSess)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
