# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqBatchSendMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ReqSendMsg_pb2 as ReqSendMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqBatchSendMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqBatchSendMsg.proto\x12\x05\x62link\x1a\x10ReqSendMsg.proto\";\n\x0fReqBatchSendMsg\x12(\n\rsend_msg_list\x18\x01 \x03(\x0b\x32\x11.blink.ReqSendMsgB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[ReqSendMsg__pb2.DESCRIPTOR,])




_REQBATCHSENDMSG = _descriptor.Descriptor(
  name='ReqBatchSendMsg',
  full_name='blink.ReqBatchSendMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='send_msg_list', full_name='blink.ReqBatchSendMsg.send_msg_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=109,
)

_REQBATCHSENDMSG.fields_by_name['send_msg_list'].message_type = ReqSendMsg__pb2._REQSENDMSG
DESCRIPTOR.message_types_by_name['ReqBatchSendMsg'] = _REQBATCHSENDMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqBatchSendMsg = _reflection.GeneratedProtocolMessageType('ReqBatchSendMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQBATCHSENDMSG,
  '__module__' : 'ReqBatchSendMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqBatchSendMsg)
  })
_sym_db.RegisterMessage(ReqBatchSendMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
