# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqBatchSessionLastMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import BatchSessions_pb2 as BatchSessions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqBatchSessionLastMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x1cReqBatchSessionLastMsg.proto\x12\x05\x62link\x1a\x13\x42\x61tchSessions.proto\"V\n\x16ReqBatchSessionLastMsg\x12\x14\n\x0creceiver_uid\x18\x01 \x02(\x04\x12&\n\x08sessions\x18\x02 \x03(\x0b\x32\x14.blink.BatchSessionsB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[BatchSessions__pb2.DESCRIPTOR,])




_REQBATCHSESSIONLASTMSG = _descriptor.Descriptor(
  name='ReqBatchSessionLastMsg',
  full_name='blink.ReqBatchSessionLastMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='receiver_uid', full_name='blink.ReqBatchSessionLastMsg.receiver_uid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sessions', full_name='blink.ReqBatchSessionLastMsg.sessions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=146,
)

_REQBATCHSESSIONLASTMSG.fields_by_name['sessions'].message_type = BatchSessions__pb2._BATCHSESSIONS
DESCRIPTOR.message_types_by_name['ReqBatchSessionLastMsg'] = _REQBATCHSESSIONLASTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqBatchSessionLastMsg = _reflection.GeneratedProtocolMessageType('ReqBatchSessionLastMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQBATCHSESSIONLASTMSG,
  '__module__' : 'ReqBatchSessionLastMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqBatchSessionLastMsg)
  })
_sym_db.RegisterMessage(ReqBatchSessionLastMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
