# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqFastLogin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqFastLogin.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12ReqFastLogin.proto\x12\x05\x62link\"\xa4\x01\n\x0cReqFastLogin\x12\x12\n\naccess_key\x18\t \x02(\t\x12\x0f\n\x07\x63onn_ip\x18\x05 \x01(\t\x12\x0e\n\x06\x64\x65v_id\x18\x04 \x02(\t\x12\x10\n\x08\x64\x65v_type\x18\x03 \x02(\x05\x12\x10\n\x08latitude\x18\x08 \x01(\x01\x12\x11\n\tlongitude\x18\x07 \x01(\x01\x12\x0c\n\x04port\x18\x06 \x01(\x05\x12\r\n\x05token\x18\x02 \x02(\t\x12\x0b\n\x03uid\x18\x01 \x02(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQFASTLOGIN = _descriptor.Descriptor(
  name='ReqFastLogin',
  full_name='blink.ReqFastLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_key', full_name='blink.ReqFastLogin.access_key', index=0,
      number=9, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conn_ip', full_name='blink.ReqFastLogin.conn_ip', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='blink.ReqFastLogin.dev_id', index=2,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_type', full_name='blink.ReqFastLogin.dev_type', index=3,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='blink.ReqFastLogin.latitude', index=4,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='blink.ReqFastLogin.longitude', index=5,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='blink.ReqFastLogin.port', index=6,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='token', full_name='blink.ReqFastLogin.token', index=7,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqFastLogin.uid', index=8,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=194,
)

DESCRIPTOR.message_types_by_name['ReqFastLogin'] = _REQFASTLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqFastLogin = _reflection.GeneratedProtocolMessageType('ReqFastLogin', (_message.Message,), {
  'DESCRIPTOR' : _REQFASTLOGIN,
  '__module__' : 'ReqFastLogin_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqFastLogin)
  })
_sym_db.RegisterMessage(ReqFastLogin)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
