# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqFresh.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqFresh.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eReqFresh.proto\x12\x05\x62link\"\x19\n\x08ReqFresh\x12\r\n\x05token\x18\x01 \x01(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQFRESH = _descriptor.Descriptor(
  name='ReqFresh',
  full_name='blink.ReqFresh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='blink.ReqFresh.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=50,
)

DESCRIPTOR.message_types_by_name['ReqFresh'] = _REQFRESH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqFresh = _reflection.GeneratedProtocolMessageType('ReqFresh', (_message.Message,), {
  'DESCRIPTOR' : _REQFRESH,
  '__module__' : 'ReqFresh_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqFresh)
  })
_sym_db.RegisterMessage(ReqFresh)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
