# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGetUsrSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqGetUsrSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16ReqGetUsrSetting.proto\x12\x05\x62link\"C\n\x10ReqGetUsrSetting\x12\x12\n\nmsg_notify\x18\x02 \x01(\x05\x12\x1b\n\x13show_unfollowed_msg\x18\x01 \x01(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQGETUSRSETTING = _descriptor.Descriptor(
  name='ReqGetUsrSetting',
  full_name='blink.ReqGetUsrSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_notify', full_name='blink.ReqGetUsrSetting.msg_notify', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_unfollowed_msg', full_name='blink.ReqGetUsrSetting.show_unfollowed_msg', index=1,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['ReqGetUsrSetting'] = _REQGETUSRSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqGetUsrSetting = _reflection.GeneratedProtocolMessageType('ReqGetUsrSetting', (_message.Message,), {
  'DESCRIPTOR' : _REQGETUSRSETTING,
  '__module__' : 'ReqGetUsrSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqGetUsrSetting)
  })
_sym_db.RegisterMessage(ReqGetUsrSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
