# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqGroupAssisMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqGroupAssisMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16ReqGroupAssisMsg.proto\x12\x05\x62link\"6\n\x10ReqGroupAssisMsg\x12\x14\n\x0c\x63lient_seqno\x18\x01 \x02(\x04\x12\x0c\n\x04size\x18\x02 \x02(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQGROUPASSISMSG = _descriptor.Descriptor(
  name='ReqGroupAssisMsg',
  full_name='blink.ReqGroupAssisMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_seqno', full_name='blink.ReqGroupAssisMsg.client_seqno', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='blink.ReqGroupAssisMsg.size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['ReqGroupAssisMsg'] = _REQGROUPASSISMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqGroupAssisMsg = _reflection.GeneratedProtocolMessageType('ReqGroupAssisMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQGROUPASSISMSG,
  '__module__' : 'ReqGroupAssisMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqGroupAssisMsg)
  })
_sym_db.RegisterMessage(ReqGroupAssisMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
