# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqHeartbeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqHeartbeat.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12ReqHeartbeat.proto\x12\x05\x62link\"G\n\x0cReqHeartbeat\x12\x12\n\nbackground\x18\x03 \x01(\x05\x12\x11\n\tmsg_seqno\x18\x01 \x02(\x04\x12\x10\n\x08op_seqno\x18\x02 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQHEARTBEAT = _descriptor.Descriptor(
  name='ReqHeartbeat',
  full_name='blink.ReqHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='background', full_name='blink.ReqHeartbeat.background', index=0,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_seqno', full_name='blink.ReqHeartbeat.msg_seqno', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op_seqno', full_name='blink.ReqHeartbeat.op_seqno', index=2,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=100,
)

DESCRIPTOR.message_types_by_name['ReqHeartbeat'] = _REQHEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqHeartbeat = _reflection.GeneratedProtocolMessageType('ReqHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _REQHEARTBEAT,
  '__module__' : 'ReqHeartbeat_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqHeartbeat)
  })
_sym_db.RegisterMessage(ReqHeartbeat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
