# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqHands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqHands.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eReqHands.proto\x12\x05\x62link\"\x17\n\x08ReqHands\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQHANDS = _descriptor.Descriptor(
  name='ReqHands',
  full_name='blink.ReqHands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqHands.uid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['ReqHands'] = _REQHANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqHands = _reflection.GeneratedProtocolMessageType('ReqHands', (_message.Message,), {
  'DESCRIPTOR' : _REQHANDS,
  '__module__' : 'ReqHands_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqHands)
  })
_sym_db.RegisterMessage(ReqHands)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
