# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqLogin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Location_pb2 as Location__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqLogin.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eReqLogin.proto\x12\x05\x62link\x1a\x0eLocation.proto\"\xce\x01\n\x08ReqLogin\x12\x12\n\naccess_key\x18\x02 \x02(\t\x12\x12\n\nauto_login\x18\n \x01(\r\x12\x0e\n\x06\x64\x65v_id\x18\x04 \x02(\t\x12\x10\n\x08\x64\x65v_type\x18\x03 \x02(\x05\x12\x12\n\nfast_token\x18\t \x01(\t\x12\x10\n\x08latitude\x18\x07 \x01(\x01\x12!\n\x08location\x18\x05 \x01(\x0b\x32\x0f.blink.Location\x12\x11\n\tlongitude\x18\x06 \x01(\x01\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x12\x0f\n\x07version\x18\x08 \x01(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Location__pb2.DESCRIPTOR,])




_REQLOGIN = _descriptor.Descriptor(
  name='ReqLogin',
  full_name='blink.ReqLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_key', full_name='blink.ReqLogin.access_key', index=0,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auto_login', full_name='blink.ReqLogin.auto_login', index=1,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='blink.ReqLogin.dev_id', index=2,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_type', full_name='blink.ReqLogin.dev_type', index=3,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fast_token', full_name='blink.ReqLogin.fast_token', index=4,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='blink.ReqLogin.latitude', index=5,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='blink.ReqLogin.location', index=6,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='blink.ReqLogin.longitude', index=7,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqLogin.uid', index=8,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='blink.ReqLogin.version', index=9,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=248,
)

_REQLOGIN.fields_by_name['location'].message_type = Location__pb2._LOCATION
DESCRIPTOR.message_types_by_name['ReqLogin'] = _REQLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqLogin = _reflection.GeneratedProtocolMessageType('ReqLogin', (_message.Message,), {
  'DESCRIPTOR' : _REQLOGIN,
  '__module__' : 'ReqLogin_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqLogin)
  })
_sym_db.RegisterMessage(ReqLogin)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
