# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqMsgSync.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqMsgSync.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10ReqMsgSync.proto\x12\x05\x62link\"d\n\nReqMsgSync\x12\x14\n\x0c\x63lient_seqno\x18\x01 \x02(\x04\x12\x0e\n\x06\x64\x65v_id\x18\x05 \x01(\t\x12\x10\n\x08has_self\x18\x04 \x01(\x08\x12\x11\n\tmsg_count\x18\x02 \x01(\r\x12\x0b\n\x03uid\x18\x03 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQMSGSYNC = _descriptor.Descriptor(
  name='ReqMsgSync',
  full_name='blink.ReqMsgSync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_seqno', full_name='blink.ReqMsgSync.client_seqno', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='blink.ReqMsgSync.dev_id', index=1,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='has_self', full_name='blink.ReqMsgSync.has_self', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg_count', full_name='blink.ReqMsgSync.msg_count', index=3,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqMsgSync.uid', index=4,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['ReqMsgSync'] = _REQMSGSYNC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqMsgSync = _reflection.GeneratedProtocolMessageType('ReqMsgSync', (_message.Message,), {
  'DESCRIPTOR' : _REQMSGSYNC,
  '__module__' : 'ReqMsgSync_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqMsgSync)
  })
_sym_db.RegisterMessage(ReqMsgSync)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
