# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqNewSessions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqNewSessions.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14ReqNewSessions.proto\x12\x05\x62link\"0\n\x0eReqNewSessions\x12\x10\n\x08\x62\x65gin_ts\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQNEWSESSIONS = _descriptor.Descriptor(
  name='ReqNewSessions',
  full_name='blink.ReqNewSessions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_ts', full_name='blink.ReqNewSessions.begin_ts', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='blink.ReqNewSessions.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=79,
)

DESCRIPTOR.message_types_by_name['ReqNewSessions'] = _REQNEWSESSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqNewSessions = _reflection.GeneratedProtocolMessageType('ReqNewSessions', (_message.Message,), {
  'DESCRIPTOR' : _REQNEWSESSIONS,
  '__module__' : 'ReqNewSessions_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqNewSessions)
  })
_sym_db.RegisterMessage(ReqNewSessions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
