# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqPushNightSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqPushNightSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19ReqPushNightSetting.proto\x12\x05\x62link\"9\n\x13ReqPushNightSetting\x12\x0e\n\x06\x61pp_id\x18\x01 \x02(\x05\x12\x12\n\npush_state\x18\x02 \x02(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQPUSHNIGHTSETTING = _descriptor.Descriptor(
  name='ReqPushNightSetting',
  full_name='blink.ReqPushNightSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='blink.ReqPushNightSetting.app_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='push_state', full_name='blink.ReqPushNightSetting.push_state', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['ReqPushNightSetting'] = _REQPUSHNIGHTSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqPushNightSetting = _reflection.GeneratedProtocolMessageType('ReqPushNightSetting', (_message.Message,), {
  'DESCRIPTOR' : _REQPUSHNIGHTSETTING,
  '__module__' : 'ReqPushNightSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqPushNightSetting)
  })
_sym_db.RegisterMessage(ReqPushNightSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
