# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqPushTotalSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqPushTotalSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19ReqPushTotalSetting.proto\x12\x05\x62link\">\n\x13ReqPushTotalSetting\x12\x13\n\x0b\x62usiness_id\x18\x01 \x02(\x05\x12\x12\n\npush_state\x18\x02 \x02(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQPUSHTOTALSETTING = _descriptor.Descriptor(
  name='ReqPushTotalSetting',
  full_name='blink.ReqPushTotalSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='business_id', full_name='blink.ReqPushTotalSetting.business_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='push_state', full_name='blink.ReqPushTotalSetting.push_state', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['ReqPushTotalSetting'] = _REQPUSHTOTALSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqPushTotalSetting = _reflection.GeneratedProtocolMessageType('ReqPushTotalSetting', (_message.Message,), {
  'DESCRIPTOR' : _REQPUSHTOTALSETTING,
  '__module__' : 'ReqPushTotalSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqPushTotalSetting)
  })
_sym_db.RegisterMessage(ReqPushTotalSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
