# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqRemoveFriend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqRemoveFriend.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqRemoveFriend.proto\x12\x05\x62link\"2\n\x0fReqRemoveFriend\x12\x12\n\nfriend_uid\x18\x02 \x02(\x04\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQREMOVEFRIEND = _descriptor.Descriptor(
  name='ReqRemoveFriend',
  full_name='blink.ReqRemoveFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_uid', full_name='blink.ReqRemoveFriend.friend_uid', index=0,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqRemoveFriend.uid', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=82,
)

DESCRIPTOR.message_types_by_name['ReqRemoveFriend'] = _REQREMOVEFRIEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqRemoveFriend = _reflection.GeneratedProtocolMessageType('ReqRemoveFriend', (_message.Message,), {
  'DESCRIPTOR' : _REQREMOVEFRIEND,
  '__module__' : 'ReqRemoveFriend_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqRemoveFriend)
  })
_sym_db.RegisterMessage(ReqRemoveFriend)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
