# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqRemoveSession.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqRemoveSession.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16ReqRemoveSession.proto\x12\x05\x62link\";\n\x10ReqRemoveSession\x12\x14\n\x0csession_type\x18\x02 \x02(\r\x12\x11\n\ttalker_id\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQREMOVESESSION = _descriptor.Descriptor(
  name='ReqRemoveSession',
  full_name='blink.ReqRemoveSession',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session_type', full_name='blink.ReqRemoveSession.session_type', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='talker_id', full_name='blink.ReqRemoveSession.talker_id', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['ReqRemoveSession'] = _REQREMOVESESSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqRemoveSession = _reflection.GeneratedProtocolMessageType('ReqRemoveSession', (_message.Message,), {
  'DESCRIPTOR' : _REQREMOVESESSION,
  '__module__' : 'ReqRemoveSession_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqRemoveSession)
  })
_sym_db.RegisterMessage(ReqRemoveSession)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
