# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSyncPushSet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSyncPushSet.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14ReqSyncPushSet.proto\x12\x05\x62link\"\x10\n\x0eReqSyncPushSetB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSYNCPUSHSET = _descriptor.Descriptor(
  name='ReqSyncPushSet',
  full_name='blink.ReqSyncPushSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=47,
)

DESCRIPTOR.message_types_by_name['ReqSyncPushSet'] = _REQSYNCPUSHSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSyncPushSet = _reflection.GeneratedProtocolMessageType('ReqSyncPushSet', (_message.Message,), {
  'DESCRIPTOR' : _REQSYNCPUSHSET,
  '__module__' : 'ReqSyncPushSet_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSyncPushSet)
  })
_sym_db.RegisterMessage(ReqSyncPushSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
