# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSingleUnread.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSingleUnread.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqSingleUnread.proto\x12\x05\x62link\"B\n\x0fReqSingleUnread\x12\x1a\n\x12show_unfollow_list\x18\x02 \x01(\r\x12\x13\n\x0bunread_type\x18\x01 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSINGLEUNREAD = _descriptor.Descriptor(
  name='ReqSingleUnread',
  full_name='blink.ReqSingleUnread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='show_unfollow_list', full_name='blink.ReqSingleUnread.show_unfollow_list', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unread_type', full_name='blink.ReqSingleUnread.unread_type', index=1,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['ReqSingleUnread'] = _REQSINGLEUNREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSingleUnread = _reflection.GeneratedProtocolMessageType('ReqSingleUnread', (_message.Message,), {
  'DESCRIPTOR' : _REQSINGLEUNREAD,
  '__module__' : 'ReqSingleUnread_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSingleUnread)
  })
_sym_db.RegisterMessage(ReqSingleUnread)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
