# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSessionInfos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSessionInfos.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqSessionInfos.proto\x12\x05\x62link\"L\n\x0fReqSessionInfos\x12\x10\n\x08need_all\x18\x03 \x01(\r\x12\x13\n\x0breceiver_id\x18\x01 \x02(\x04\x12\x12\n\nsender_uid\x18\x02 \x03(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSESSIONINFOS = _descriptor.Descriptor(
  name='ReqSessionInfos',
  full_name='blink.ReqSessionInfos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='need_all', full_name='blink.ReqSessionInfos.need_all', index=0,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='blink.ReqSessionInfos.receiver_id', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender_uid', full_name='blink.ReqSessionInfos.sender_uid', index=2,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['ReqSessionInfos'] = _REQSESSIONINFOS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSessionInfos = _reflection.GeneratedProtocolMessageType('ReqSessionInfos', (_message.Message,), {
  'DESCRIPTOR' : _REQSESSIONINFOS,
  '__module__' : 'ReqSessionInfos_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSessionInfos)
  })
_sym_db.RegisterMessage(ReqSessionInfos)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
