# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSendMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Msg_pb2 as Msg__pb2
from . import ExtInfo_pb2 as ExtInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSendMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10ReqSendMsg.proto\x12\x05\x62link\x1a\tMsg.proto\x1a\rExtInfo.proto\"\xc1\x01\n\nReqSendMsg\x12\x0e\n\x06\x63ookie\x18\x03 \x01(\t\x12\x0f\n\x07\x63ookie2\x18\x04 \x01(\t\x12\x0e\n\x06\x64\x65v_id\x18\x07 \x01(\t\x12\x12\n\nerror_code\x18\x06 \x01(\x05\x12 \n\x08\x65xt_info\x18\t \x01(\x0b\x32\x0e.blink.ExtInfo\x12\x0f\n\x07instant\x18\x02 \x01(\x08\x12\x17\n\x03msg\x18\x01 \x02(\x0b\x32\n.blink.Msg\x12\x14\n\x0cofficial_msg\x18\x05 \x01(\x05\x12\x0c\n\x04sync\x18\x08 \x01(\x08\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Msg__pb2.DESCRIPTOR,ExtInfo__pb2.DESCRIPTOR,])




_REQSENDMSG = _descriptor.Descriptor(
  name='ReqSendMsg',
  full_name='blink.ReqSendMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cookie', full_name='blink.ReqSendMsg.cookie', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cookie2', full_name='blink.ReqSendMsg.cookie2', index=1,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_id', full_name='blink.ReqSendMsg.dev_id', index=2,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='blink.ReqSendMsg.error_code', index=3,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ext_info', full_name='blink.ReqSendMsg.ext_info', index=4,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instant', full_name='blink.ReqSendMsg.instant', index=5,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='blink.ReqSendMsg.msg', index=6,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='official_msg', full_name='blink.ReqSendMsg.official_msg', index=7,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sync', full_name='blink.ReqSendMsg.sync', index=8,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=247,
)

_REQSENDMSG.fields_by_name['ext_info'].message_type = ExtInfo__pb2._EXTINFO
_REQSENDMSG.fields_by_name['msg'].message_type = Msg__pb2._MSG
DESCRIPTOR.message_types_by_name['ReqSendMsg'] = _REQSENDMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSendMsg = _reflection.GeneratedProtocolMessageType('ReqSendMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQSENDMSG,
  '__module__' : 'ReqSendMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSendMsg)
  })
_sym_db.RegisterMessage(ReqSendMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
