# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqServerNotify.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Msg_pb2 as Msg__pb2
from . import NotifyInfo_pb2 as NotifyInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqServerNotify.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqServerNotify.proto\x12\x05\x62link\x1a\tMsg.proto\x1a\x10NotifyInfo.proto\"q\n\x0fReqServerNotify\x12\x1f\n\x0binstant_msg\x18\x02 \x01(\x0b\x32\n.blink.Msg\x12\x15\n\rlastest_seqno\x18\x01 \x02(\x04\x12&\n\x0bnotify_info\x18\x03 \x01(\x0b\x32\x11.blink.NotifyInfoB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Msg__pb2.DESCRIPTOR,NotifyInfo__pb2.DESCRIPTOR,])




_REQSERVERNOTIFY = _descriptor.Descriptor(
  name='ReqServerNotify',
  full_name='blink.ReqServerNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instant_msg', full_name='blink.ReqServerNotify.instant_msg', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lastest_seqno', full_name='blink.ReqServerNotify.lastest_seqno', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='notify_info', full_name='blink.ReqServerNotify.notify_info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=174,
)

_REQSERVERNOTIFY.fields_by_name['instant_msg'].message_type = Msg__pb2._MSG
_REQSERVERNOTIFY.fields_by_name['notify_info'].message_type = NotifyInfo__pb2._NOTIFYINFO
DESCRIPTOR.message_types_by_name['ReqServerNotify'] = _REQSERVERNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqServerNotify = _reflection.GeneratedProtocolMessageType('ReqServerNotify', (_message.Message,), {
  'DESCRIPTOR' : _REQSERVERNOTIFY,
  '__module__' : 'ReqServerNotify_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqServerNotify)
  })
_sym_db.RegisterMessage(ReqServerNotify)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
