# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSearch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSearch.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0fReqSearch.proto\x12\x05\x62link\"\'\n\tReqSearch\x12\x0c\n\x04\x66lag\x18\x02 \x01(\x05\x12\x0c\n\x04what\x18\x01 \x02(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSEARCH = _descriptor.Descriptor(
  name='ReqSearch',
  full_name='blink.ReqSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='flag', full_name='blink.ReqSearch.flag', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='what', full_name='blink.ReqSearch.what', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=65,
)

DESCRIPTOR.message_types_by_name['ReqSearch'] = _REQSEARCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSearch = _reflection.GeneratedProtocolMessageType('ReqSearch', (_message.Message,), {
  'DESCRIPTOR' : _REQSEARCH,
  '__module__' : 'ReqSearch_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSearch)
  })
_sym_db.RegisterMessage(ReqSearch)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
