# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSyncAck.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSyncAck.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10ReqSyncAck.proto\x12\x05\x62link\"\"\n\nReqSyncAck\x12\x14\n\x0c\x63lient_seqno\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSYNCACK = _descriptor.Descriptor(
  name='ReqSyncAck',
  full_name='blink.ReqSyncAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_seqno', full_name='blink.ReqSyncAck.client_seqno', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['ReqSyncAck'] = _REQSYNCACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSyncAck = _reflection.GeneratedProtocolMessageType('ReqSyncAck', (_message.Message,), {
  'DESCRIPTOR' : _REQSYNCACK,
  '__module__' : 'ReqSyncAck_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSyncAck)
  })
_sym_db.RegisterMessage(ReqSyncAck)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
