# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSessionMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSessionMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x13ReqSessionMsg.proto\x12\x05\x62link\"}\n\rReqSessionMsg\x12\x13\n\x0b\x62\x65gin_seqno\x18\x04 \x01(\x04\x12\x11\n\tend_seqno\x18\x03 \x01(\x04\x12\r\n\x05order\x18\x06 \x01(\x05\x12\x14\n\x0csession_type\x18\x02 \x02(\x05\x12\x0c\n\x04size\x18\x05 \x01(\x05\x12\x11\n\ttalker_id\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSESSIONMSG = _descriptor.Descriptor(
  name='ReqSessionMsg',
  full_name='blink.ReqSessionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='begin_seqno', full_name='blink.ReqSessionMsg.begin_seqno', index=0,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_seqno', full_name='blink.ReqSessionMsg.end_seqno', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='order', full_name='blink.ReqSessionMsg.order', index=2,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_type', full_name='blink.ReqSessionMsg.session_type', index=3,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='blink.ReqSessionMsg.size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='talker_id', full_name='blink.ReqSessionMsg.talker_id', index=5,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=155,
)

DESCRIPTOR.message_types_by_name['ReqSessionMsg'] = _REQSESSIONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSessionMsg = _reflection.GeneratedProtocolMessageType('ReqSessionMsg', (_message.Message,), {
  'DESCRIPTOR' : _REQSESSIONMSG,
  '__module__' : 'ReqSessionMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSessionMsg)
  })
_sym_db.RegisterMessage(ReqSessionMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
