# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSessionDetails.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ReqSessionDetail_pb2 as ReqSessionDetail__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSessionDetails.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x17ReqSessionDetails.proto\x12\x05\x62link\x1a\x16ReqSessionDetail.proto\">\n\x11ReqSessionDetails\x12)\n\x08sess_ids\x18\x01 \x03(\x0b\x32\x17.blink.ReqSessionDetailB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[ReqSessionDetail__pb2.DESCRIPTOR,])




_REQSESSIONDETAILS = _descriptor.Descriptor(
  name='ReqSessionDetails',
  full_name='blink.ReqSessionDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sess_ids', full_name='blink.ReqSessionDetails.sess_ids', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=120,
)

_REQSESSIONDETAILS.fields_by_name['sess_ids'].message_type = ReqSessionDetail__pb2._REQSESSIONDETAIL
DESCRIPTOR.message_types_by_name['ReqSessionDetails'] = _REQSESSIONDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSessionDetails = _reflection.GeneratedProtocolMessageType('ReqSessionDetails', (_message.Message,), {
  'DESCRIPTOR' : _REQSESSIONDETAILS,
  '__module__' : 'ReqSessionDetails_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSessionDetails)
  })
_sym_db.RegisterMessage(ReqSessionDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
