# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSaveToken.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSaveToken.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12ReqSaveToken.proto\x12\x05\x62link\"C\n\x0cReqSaveToken\x12\x0e\n\x06\x61pp_id\x18\x01 \x02(\x05\x12\x11\n\tdev_token\x18\x03 \x02(\t\x12\x10\n\x08\x64\x65v_type\x18\x02 \x02(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSAVETOKEN = _descriptor.Descriptor(
  name='ReqSaveToken',
  full_name='blink.ReqSaveToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app_id', full_name='blink.ReqSaveToken.app_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_token', full_name='blink.ReqSaveToken.dev_token', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dev_type', full_name='blink.ReqSaveToken.dev_type', index=2,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['ReqSaveToken'] = _REQSAVETOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSaveToken = _reflection.GeneratedProtocolMessageType('ReqSaveToken', (_message.Message,), {
  'DESCRIPTOR' : _REQSAVETOKEN,
  '__module__' : 'ReqSaveToken_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSaveToken)
  })
_sym_db.RegisterMessage(ReqSaveToken)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
