# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqSetMsgDndSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqSetMsgDndSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19ReqSetMsgDndSetting.proto\x12\x05\x62link\"Z\n\x13ReqSetMsgDndSetting\x12\x14\n\x0c\x64nd_group_id\x18\x03 \x01(\x04\x12\x0f\n\x07\x64nd_uid\x18\x02 \x01(\x04\x12\x0f\n\x07setting\x18\x04 \x02(\x05\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQSETMSGDNDSETTING = _descriptor.Descriptor(
  name='ReqSetMsgDndSetting',
  full_name='blink.ReqSetMsgDndSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dnd_group_id', full_name='blink.ReqSetMsgDndSetting.dnd_group_id', index=0,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dnd_uid', full_name='blink.ReqSetMsgDndSetting.dnd_uid', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setting', full_name='blink.ReqSetMsgDndSetting.setting', index=2,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqSetMsgDndSetting.uid', index=3,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['ReqSetMsgDndSetting'] = _REQSETMSGDNDSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqSetMsgDndSetting = _reflection.GeneratedProtocolMessageType('ReqSetMsgDndSetting', (_message.Message,), {
  'DESCRIPTOR' : _REQSETMSGDNDSETTING,
  '__module__' : 'ReqSetMsgDndSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqSetMsgDndSetting)
  })
_sym_db.RegisterMessage(ReqSetMsgDndSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
