# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUsrSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqUsrSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x13ReqUsrSetting.proto\x12\x05\x62link\"w\n\rReqUsrSetting\x12\x12\n\nmsg_notify\x18\x02 \x01(\x05\x12\x0e\n\x06set_at\x18\x05 \x01(\x05\x12\x13\n\x0bset_comment\x18\x04 \x01(\x05\x12\x10\n\x08set_like\x18\x03 \x01(\x05\x12\x1b\n\x13show_unfollowed_msg\x18\x01 \x01(\x05\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQUSRSETTING = _descriptor.Descriptor(
  name='ReqUsrSetting',
  full_name='blink.ReqUsrSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_notify', full_name='blink.ReqUsrSetting.msg_notify', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_at', full_name='blink.ReqUsrSetting.set_at', index=1,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_comment', full_name='blink.ReqUsrSetting.set_comment', index=2,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='set_like', full_name='blink.ReqUsrSetting.set_like', index=3,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='show_unfollowed_msg', full_name='blink.ReqUsrSetting.show_unfollowed_msg', index=4,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['ReqUsrSetting'] = _REQUSRSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqUsrSetting = _reflection.GeneratedProtocolMessageType('ReqUsrSetting', (_message.Message,), {
  'DESCRIPTOR' : _REQUSRSETTING,
  '__module__' : 'ReqUsrSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqUsrSetting)
  })
_sym_db.RegisterMessage(ReqUsrSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
