# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUpdateFollow.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqUpdateFollow.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15ReqUpdateFollow.proto\x12\x05\x62link\">\n\x0fReqUpdateFollow\x12\x0f\n\x07op_type\x18\x02 \x02(\x05\x12\x0b\n\x03uid\x18\x03 \x02(\x04\x12\r\n\x05up_id\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQUPDATEFOLLOW = _descriptor.Descriptor(
  name='ReqUpdateFollow',
  full_name='blink.ReqUpdateFollow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_type', full_name='blink.ReqUpdateFollow.op_type', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.ReqUpdateFollow.uid', index=1,
      number=3, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='up_id', full_name='blink.ReqUpdateFollow.up_id', index=2,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=94,
)

DESCRIPTOR.message_types_by_name['ReqUpdateFollow'] = _REQUPDATEFOLLOW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqUpdateFollow = _reflection.GeneratedProtocolMessageType('ReqUpdateFollow', (_message.Message,), {
  'DESCRIPTOR' : _REQUPDATEFOLLOW,
  '__module__' : 'ReqUpdateFollow_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqUpdateFollow)
  })
_sym_db.RegisterMessage(ReqUpdateFollow)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
