# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ReqUpdateSessionDnd.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ReqUpdateSessionDnd.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19ReqUpdateSessionDnd.proto\x12\x05\x62link\"\x15\n\x13ReqUpdateSessionDndB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_REQUPDATESESSIONDND = _descriptor.Descriptor(
  name='ReqUpdateSessionDnd',
  full_name='blink.ReqUpdateSessionDnd',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['ReqUpdateSessionDnd'] = _REQUPDATESESSIONDND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReqUpdateSessionDnd = _reflection.GeneratedProtocolMessageType('ReqUpdateSessionDnd', (_message.Message,), {
  'DESCRIPTOR' : _REQUPDATESESSIONDND,
  '__module__' : 'ReqUpdateSessionDnd_pb2'
  # @@protoc_insertion_point(class_scope:blink.ReqUpdateSessionDnd)
  })
_sym_db.RegisterMessage(ReqUpdateSessionDnd)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
