# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspAckApplyFriend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspAckApplyFriend.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x17RspAckApplyFriend.proto\x12\x05\x62link\"\x13\n\x11RspAckApplyFriendB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPACKAPPLYFRIEND = _descriptor.Descriptor(
  name='RspAckApplyFriend',
  full_name='blink.RspAckApplyFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['RspAckApplyFriend'] = _RSPACKAPPLYFRIEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspAckApplyFriend = _reflection.GeneratedProtocolMessageType('RspAckApplyFriend', (_message.Message,), {
  'DESCRIPTOR' : _RSPACKAPPLYFRIEND,
  '__module__' : 'RspAckApplyFriend_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspAckApplyFriend)
  })
_sym_db.RegisterMessage(RspAckApplyFriend)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
