# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspBatchSessionLastMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import LastMsgKey_pb2 as LastMsgKey__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspBatchSessionLastMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x1cRspBatchSessionLastMsg.proto\x12\x05\x62link\x1a\x10LastMsgKey.proto\">\n\x16RspBatchSessionLastMsg\x12$\n\tlast_msgs\x18\x01 \x03(\x0b\x32\x11.blink.LastMsgKeyB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[LastMsgKey__pb2.DESCRIPTOR,])




_RSPBATCHSESSIONLASTMSG = _descriptor.Descriptor(
  name='RspBatchSessionLastMsg',
  full_name='blink.RspBatchSessionLastMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_msgs', full_name='blink.RspBatchSessionLastMsg.last_msgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=119,
)

_RSPBATCHSESSIONLASTMSG.fields_by_name['last_msgs'].message_type = LastMsgKey__pb2._LASTMSGKEY
DESCRIPTOR.message_types_by_name['RspBatchSessionLastMsg'] = _RSPBATCHSESSIONLASTMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspBatchSessionLastMsg = _reflection.GeneratedProtocolMessageType('RspBatchSessionLastMsg', (_message.Message,), {
  'DESCRIPTOR' : _RSPBATCHSESSIONLASTMSG,
  '__module__' : 'RspBatchSessionLastMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspBatchSessionLastMsg)
  })
_sym_db.RegisterMessage(RspBatchSessionLastMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
