# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspBatchSendMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import ReqSendMsg_pb2 as ReqSendMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspBatchSendMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15RspBatchSendMsg.proto\x12\x05\x62link\x1a\x10ReqSendMsg.proto\"=\n\x0fRspBatchSendMsg\x12*\n\x0f\x66\x61iled_msg_list\x18\x01 \x03(\x0b\x32\x11.blink.ReqSendMsgB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[ReqSendMsg__pb2.DESCRIPTOR,])




_RSPBATCHSENDMSG = _descriptor.Descriptor(
  name='RspBatchSendMsg',
  full_name='blink.RspBatchSendMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_msg_list', full_name='blink.RspBatchSendMsg.failed_msg_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=111,
)

_RSPBATCHSENDMSG.fields_by_name['failed_msg_list'].message_type = ReqSendMsg__pb2._REQSENDMSG
DESCRIPTOR.message_types_by_name['RspBatchSendMsg'] = _RSPBATCHSENDMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspBatchSendMsg = _reflection.GeneratedProtocolMessageType('RspBatchSendMsg', (_message.Message,), {
  'DESCRIPTOR' : _RSPBATCHSENDMSG,
  '__module__' : 'RspBatchSendMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspBatchSendMsg)
  })
_sym_db.RegisterMessage(RspBatchSendMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
