# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspFresh.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspFresh.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eRspFresh.proto\x12\x05\x62link\"\n\n\x08RspFreshB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPFRESH = _descriptor.Descriptor(
  name='RspFresh',
  full_name='blink.RspFresh',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=35,
)

DESCRIPTOR.message_types_by_name['RspFresh'] = _RSPFRESH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspFresh = _reflection.GeneratedProtocolMessageType('RspFresh', (_message.Message,), {
  'DESCRIPTOR' : _RSPFRESH,
  '__module__' : 'RspFresh_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspFresh)
  })
_sym_db.RegisterMessage(RspFresh)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
