# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspGetMsgDndSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Setting_pb2 as Setting__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspGetMsgDndSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19RspGetMsgDndSetting.proto\x12\x05\x62link\x1a\rSetting.proto\"c\n\x13RspGetMsgDndSetting\x12&\n\x0egroup_settings\x18\x02 \x03(\x0b\x32\x0e.blink.Setting\x12$\n\x0cuid_settings\x18\x01 \x03(\x0b\x32\x0e.blink.SettingB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Setting__pb2.DESCRIPTOR,])




_RSPGETMSGDNDSETTING = _descriptor.Descriptor(
  name='RspGetMsgDndSetting',
  full_name='blink.RspGetMsgDndSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='group_settings', full_name='blink.RspGetMsgDndSetting.group_settings', index=0,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid_settings', full_name='blink.RspGetMsgDndSetting.uid_settings', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=150,
)

_RSPGETMSGDNDSETTING.fields_by_name['group_settings'].message_type = Setting__pb2._SETTING
_RSPGETMSGDNDSETTING.fields_by_name['uid_settings'].message_type = Setting__pb2._SETTING
DESCRIPTOR.message_types_by_name['RspGetMsgDndSetting'] = _RSPGETMSGDNDSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspGetMsgDndSetting = _reflection.GeneratedProtocolMessageType('RspGetMsgDndSetting', (_message.Message,), {
  'DESCRIPTOR' : _RSPGETMSGDNDSETTING,
  '__module__' : 'RspGetMsgDndSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspGetMsgDndSetting)
  })
_sym_db.RegisterMessage(RspGetMsgDndSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
