# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspHands.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspHands.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eRspHands.proto\x12\x05\x62link\"\x18\n\x08RspHands\x12\x0c\n\x04skey\x18\x01 \x01(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPHANDS = _descriptor.Descriptor(
  name='RspHands',
  full_name='blink.RspHands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skey', full_name='blink.RspHands.skey', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['RspHands'] = _RSPHANDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspHands = _reflection.GeneratedProtocolMessageType('RspHands', (_message.Message,), {
  'DESCRIPTOR' : _RSPHANDS,
  '__module__' : 'RspHands_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspHands)
  })
_sym_db.RegisterMessage(RspHands)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
