# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspHeartbeat.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspHeartbeat.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12RspHeartbeat.proto\x12\x05\x62link\"?\n\x0cRspHeartbeat\x12\x19\n\x11heartbeat_timeout\x18\x02 \x02(\r\x12\x14\n\x0clatest_seqno\x18\x01 \x02(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPHEARTBEAT = _descriptor.Descriptor(
  name='RspHeartbeat',
  full_name='blink.RspHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='heartbeat_timeout', full_name='blink.RspHeartbeat.heartbeat_timeout', index=0,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='latest_seqno', full_name='blink.RspHeartbeat.latest_seqno', index=1,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=92,
)

DESCRIPTOR.message_types_by_name['RspHeartbeat'] = _RSPHEARTBEAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspHeartbeat = _reflection.GeneratedProtocolMessageType('RspHeartbeat', (_message.Message,), {
  'DESCRIPTOR' : _RSPHEARTBEAT,
  '__module__' : 'RspHeartbeat_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspHeartbeat)
  })
_sym_db.RegisterMessage(RspHeartbeat)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
