# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspIsLimit.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspIsLimit.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10RspIsLimit.proto\x12\x05\x62link\"1\n\nRspIsLimit\x12\x10\n\x08is_limit\x18\x01 \x02(\x05\x12\x11\n\tlimit_msg\x18\x02 \x01(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPISLIMIT = _descriptor.Descriptor(
  name='RspIsLimit',
  full_name='blink.RspIsLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_limit', full_name='blink.RspIsLimit.is_limit', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='limit_msg', full_name='blink.RspIsLimit.limit_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=76,
)

DESCRIPTOR.message_types_by_name['RspIsLimit'] = _RSPISLIMIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspIsLimit = _reflection.GeneratedProtocolMessageType('RspIsLimit', (_message.Message,), {
  'DESCRIPTOR' : _RSPISLIMIT,
  '__module__' : 'RspIsLimit_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspIsLimit)
  })
_sym_db.RegisterMessage(RspIsLimit)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
