# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspLogin.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspLogin.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0eRspLogin.proto\x12\x05\x62link\"_\n\x08RspLogin\x12\x15\n\rlatest_mss_ts\x18\x04 \x01(\x04\x12\x12\n\nnext_token\x18\x01 \x01(\t\x12\x1b\n\x13server_latest_seqno\x18\x02 \x01(\x04\x12\x0b\n\x03uid\x18\x03 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPLOGIN = _descriptor.Descriptor(
  name='RspLogin',
  full_name='blink.RspLogin',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latest_mss_ts', full_name='blink.RspLogin.latest_mss_ts', index=0,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_token', full_name='blink.RspLogin.next_token', index=1,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server_latest_seqno', full_name='blink.RspLogin.server_latest_seqno', index=2,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.RspLogin.uid', index=3,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=120,
)

DESCRIPTOR.message_types_by_name['RspLogin'] = _RSPLOGIN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspLogin = _reflection.GeneratedProtocolMessageType('RspLogin', (_message.Message,), {
  'DESCRIPTOR' : _RSPLOGIN,
  '__module__' : 'RspLogin_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspLogin)
  })
_sym_db.RegisterMessage(RspLogin)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
