# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspMyGroupUnread.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspMyGroupUnread.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16RspMyGroupUnread.proto\x12\x05\x62link\"(\n\x10RspMyGroupUnread\x12\x14\n\x0cunread_count\x18\x01 \x01(\rB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPMYGROUPUNREAD = _descriptor.Descriptor(
  name='RspMyGroupUnread',
  full_name='blink.RspMyGroupUnread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unread_count', full_name='blink.RspMyGroupUnread.unread_count', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['RspMyGroupUnread'] = _RSPMYGROUPUNREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspMyGroupUnread = _reflection.GeneratedProtocolMessageType('RspMyGroupUnread', (_message.Message,), {
  'DESCRIPTOR' : _RSPMYGROUPUNREAD,
  '__module__' : 'RspMyGroupUnread_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspMyGroupUnread)
  })
_sym_db.RegisterMessage(RspMyGroupUnread)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
