# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspPushTotalSetting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspPushTotalSetting.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x19RspPushTotalSetting.proto\x12\x05\x62link\"\x15\n\x13RspPushTotalSettingB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPPUSHTOTALSETTING = _descriptor.Descriptor(
  name='RspPushTotalSetting',
  full_name='blink.RspPushTotalSetting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['RspPushTotalSetting'] = _RSPPUSHTOTALSETTING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspPushTotalSetting = _reflection.GeneratedProtocolMessageType('RspPushTotalSetting', (_message.Message,), {
  'DESCRIPTOR' : _RSPPUSHTOTALSETTING,
  '__module__' : 'RspPushTotalSetting_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspPushTotalSetting)
  })
_sym_db.RegisterMessage(RspPushTotalSetting)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
