# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspRemoveFriend.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspRemoveFriend.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15RspRemoveFriend.proto\x12\x05\x62link\"\x11\n\x0fRspRemoveFriendB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPREMOVEFRIEND = _descriptor.Descriptor(
  name='RspRemoveFriend',
  full_name='blink.RspRemoveFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['RspRemoveFriend'] = _RSPREMOVEFRIEND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspRemoveFriend = _reflection.GeneratedProtocolMessageType('RspRemoveFriend', (_message.Message,), {
  'DESCRIPTOR' : _RSPREMOVEFRIEND,
  '__module__' : 'RspRemoveFriend_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspRemoveFriend)
  })
_sym_db.RegisterMessage(RspRemoveFriend)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
