# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspServerNotify.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspServerNotify.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15RspServerNotify.proto\x12\x05\x62link\"\x11\n\x0fRspServerNotifyB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPSERVERNOTIFY = _descriptor.Descriptor(
  name='RspServerNotify',
  full_name='blink.RspServerNotify',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=49,
)

DESCRIPTOR.message_types_by_name['RspServerNotify'] = _RSPSERVERNOTIFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspServerNotify = _reflection.GeneratedProtocolMessageType('RspServerNotify', (_message.Message,), {
  'DESCRIPTOR' : _RSPSERVERNOTIFY,
  '__module__' : 'RspServerNotify_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspServerNotify)
  })
_sym_db.RegisterMessage(RspServerNotify)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
