# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspServerKickOff.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspServerKickOff.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16RspServerKickOff.proto\x12\x05\x62link\"\x12\n\x10RspServerKickOffB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPSERVERKICKOFF = _descriptor.Descriptor(
  name='RspServerKickOff',
  full_name='blink.RspServerKickOff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=51,
)

DESCRIPTOR.message_types_by_name['RspServerKickOff'] = _RSPSERVERKICKOFF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspServerKickOff = _reflection.GeneratedProtocolMessageType('RspServerKickOff', (_message.Message,), {
  'DESCRIPTOR' : _RSPSERVERKICKOFF,
  '__module__' : 'RspServerKickOff_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspServerKickOff)
  })
_sym_db.RegisterMessage(RspServerKickOff)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
