# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSessions.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SessionInfo_pb2 as SessionInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSessions.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x11RspSessions.proto\x12\x05\x62link\x1a\x11SessionInfo.proto\"I\n\x0bRspSessions\x12\x10\n\x08has_more\x18\x02 \x01(\r\x12(\n\x0csession_list\x18\x01 \x03(\x0b\x32\x12.blink.SessionInfoB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[SessionInfo__pb2.DESCRIPTOR,])




_RSPSESSIONS = _descriptor.Descriptor(
  name='RspSessions',
  full_name='blink.RspSessions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_more', full_name='blink.RspSessions.has_more', index=0,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='session_list', full_name='blink.RspSessions.session_list', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=120,
)

_RSPSESSIONS.fields_by_name['session_list'].message_type = SessionInfo__pb2._SESSIONINFO
DESCRIPTOR.message_types_by_name['RspSessions'] = _RSPSESSIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSessions = _reflection.GeneratedProtocolMessageType('RspSessions', (_message.Message,), {
  'DESCRIPTOR' : _RSPSESSIONS,
  '__module__' : 'RspSessions_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSessions)
  })
_sym_db.RegisterMessage(RspSessions)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
