# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSessionDetails.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SessionInfo_pb2 as SessionInfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSessionDetails.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x17RspSessionDetails.proto\x12\x05\x62link\x1a\x11SessionInfo.proto\";\n\x11RspSessionDetails\x12&\n\nsess_infos\x18\x01 \x03(\x0b\x32\x12.blink.SessionInfoB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[SessionInfo__pb2.DESCRIPTOR,])




_RSPSESSIONDETAILS = _descriptor.Descriptor(
  name='RspSessionDetails',
  full_name='blink.RspSessionDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sess_infos', full_name='blink.RspSessionDetails.sess_infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=112,
)

_RSPSESSIONDETAILS.fields_by_name['sess_infos'].message_type = SessionInfo__pb2._SESSIONINFO
DESCRIPTOR.message_types_by_name['RspSessionDetails'] = _RSPSESSIONDETAILS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSessionDetails = _reflection.GeneratedProtocolMessageType('RspSessionDetails', (_message.Message,), {
  'DESCRIPTOR' : _RSPSESSIONDETAILS,
  '__module__' : 'RspSessionDetails_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSessionDetails)
  })
_sym_db.RegisterMessage(RspSessionDetails)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
