# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSaveToken.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSaveToken.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12RspSaveToken.proto\x12\x05\x62link\"\x0e\n\x0cRspSaveTokenB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPSAVETOKEN = _descriptor.Descriptor(
  name='RspSaveToken',
  full_name='blink.RspSaveToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=43,
)

DESCRIPTOR.message_types_by_name['RspSaveToken'] = _RSPSAVETOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSaveToken = _reflection.GeneratedProtocolMessageType('RspSaveToken', (_message.Message,), {
  'DESCRIPTOR' : _RSPSAVETOKEN,
  '__module__' : 'RspSaveToken_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSaveToken)
  })
_sym_db.RegisterMessage(RspSaveToken)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
