# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSendMsgs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import UidCodeMsg_pb2 as UidCodeMsg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSendMsgs.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x11RspSendMsgs.proto\x12\x05\x62link\x1a\x10UidCodeMsg.proto\"5\n\x0bRspSendMsgs\x12&\n\x0b\x66\x61iled_msgs\x18\x01 \x03(\x0b\x32\x11.blink.UidCodeMsgB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[UidCodeMsg__pb2.DESCRIPTOR,])




_RSPSENDMSGS = _descriptor.Descriptor(
  name='RspSendMsgs',
  full_name='blink.RspSendMsgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='failed_msgs', full_name='blink.RspSendMsgs.failed_msgs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=99,
)

_RSPSENDMSGS.fields_by_name['failed_msgs'].message_type = UidCodeMsg__pb2._UIDCODEMSG
DESCRIPTOR.message_types_by_name['RspSendMsgs'] = _RSPSENDMSGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSendMsgs = _reflection.GeneratedProtocolMessageType('RspSendMsgs', (_message.Message,), {
  'DESCRIPTOR' : _RSPSENDMSGS,
  '__module__' : 'RspSendMsgs_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSendMsgs)
  })
_sym_db.RegisterMessage(RspSendMsgs)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
