# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSyncPushSet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SyncPushSetting_pb2 as SyncPushSetting__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSyncPushSet.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x14RspSyncPushSet.proto\x12\x05\x62link\x1a\x15SyncPushSetting.proto\"?\n\x0eRspSyncPushSet\x12-\n\rpush_settings\x18\x01 \x03(\x0b\x32\x16.blink.SyncPushSettingB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[SyncPushSetting__pb2.DESCRIPTOR,])




_RSPSYNCPUSHSET = _descriptor.Descriptor(
  name='RspSyncPushSet',
  full_name='blink.RspSyncPushSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='push_settings', full_name='blink.RspSyncPushSet.push_settings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=117,
)

_RSPSYNCPUSHSET.fields_by_name['push_settings'].message_type = SyncPushSetting__pb2._SYNCPUSHSETTING
DESCRIPTOR.message_types_by_name['RspSyncPushSet'] = _RSPSYNCPUSHSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSyncPushSet = _reflection.GeneratedProtocolMessageType('RspSyncPushSet', (_message.Message,), {
  'DESCRIPTOR' : _RSPSYNCPUSHSET,
  '__module__' : 'RspSyncPushSet_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSyncPushSet)
  })
_sym_db.RegisterMessage(RspSyncPushSet)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
