# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSearch.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import GroupDesc_pb2 as GroupDesc__pb2
from . import UserDesc_pb2 as UserDesc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSearch.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0fRspSearch.proto\x12\x05\x62link\x1a\x0fGroupDesc.proto\x1a\x0eUserDesc.proto\"M\n\tRspSearch\x12 \n\x06groups\x18\x01 \x03(\x0b\x32\x10.blink.GroupDesc\x12\x1e\n\x05users\x18\x02 \x03(\x0b\x32\x0f.blink.UserDescB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[GroupDesc__pb2.DESCRIPTOR,UserDesc__pb2.DESCRIPTOR,])




_RSPSEARCH = _descriptor.Descriptor(
  name='RspSearch',
  full_name='blink.RspSearch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='groups', full_name='blink.RspSearch.groups', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='blink.RspSearch.users', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=136,
)

_RSPSEARCH.fields_by_name['groups'].message_type = GroupDesc__pb2._GROUPDESC
_RSPSEARCH.fields_by_name['users'].message_type = UserDesc__pb2._USERDESC
DESCRIPTOR.message_types_by_name['RspSearch'] = _RSPSEARCH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSearch = _reflection.GeneratedProtocolMessageType('RspSearch', (_message.Message,), {
  'DESCRIPTOR' : _RSPSEARCH,
  '__module__' : 'RspSearch_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSearch)
  })
_sym_db.RegisterMessage(RspSearch)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
