# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSingleUnread.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSingleUnread.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x15RspSingleUnread.proto\x12\x05\x62link\"\\\n\x0fRspSingleUnread\x12\x15\n\rfollow_unread\x18\x02 \x01(\x04\x12\x19\n\x11unfollow_push_msg\x18\x03 \x01(\r\x12\x17\n\x0funfollow_unread\x18\x01 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPSINGLEUNREAD = _descriptor.Descriptor(
  name='RspSingleUnread',
  full_name='blink.RspSingleUnread',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='follow_unread', full_name='blink.RspSingleUnread.follow_unread', index=0,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unfollow_push_msg', full_name='blink.RspSingleUnread.unfollow_push_msg', index=1,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unfollow_unread', full_name='blink.RspSingleUnread.unfollow_unread', index=2,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=124,
)

DESCRIPTOR.message_types_by_name['RspSingleUnread'] = _RSPSINGLEUNREAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSingleUnread = _reflection.GeneratedProtocolMessageType('RspSingleUnread', (_message.Message,), {
  'DESCRIPTOR' : _RSPSINGLEUNREAD,
  '__module__' : 'RspSingleUnread_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSingleUnread)
  })
_sym_db.RegisterMessage(RspSingleUnread)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
