# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSessionMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Msg_pb2 as Msg__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSessionMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x13RspSessionMsg.proto\x12\x05\x62link\x1a\tMsg.proto\"e\n\rRspSessionMsg\x12\x10\n\x08has_more\x18\x02 \x01(\x05\x12\x11\n\tmax_seqno\x18\x04 \x01(\x04\x12\x1c\n\x08messages\x18\x01 \x03(\x0b\x32\n.blink.Msg\x12\x11\n\tmin_seqno\x18\x03 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[Msg__pb2.DESCRIPTOR,])




_RSPSESSIONMSG = _descriptor.Descriptor(
  name='RspSessionMsg',
  full_name='blink.RspSessionMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='has_more', full_name='blink.RspSessionMsg.has_more', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_seqno', full_name='blink.RspSessionMsg.max_seqno', index=1,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='messages', full_name='blink.RspSessionMsg.messages', index=2,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='min_seqno', full_name='blink.RspSessionMsg.min_seqno', index=3,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=142,
)

_RSPSESSIONMSG.fields_by_name['messages'].message_type = Msg__pb2._MSG
DESCRIPTOR.message_types_by_name['RspSessionMsg'] = _RSPSESSIONMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSessionMsg = _reflection.GeneratedProtocolMessageType('RspSessionMsg', (_message.Message,), {
  'DESCRIPTOR' : _RSPSESSIONMSG,
  '__module__' : 'RspSessionMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSessionMsg)
  })
_sym_db.RegisterMessage(RspSessionMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
