# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspSyncAck.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspSyncAck.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10RspSyncAck.proto\x12\x05\x62link\"\x0c\n\nRspSyncAckB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPSYNCACK = _descriptor.Descriptor(
  name='RspSyncAck',
  full_name='blink.RspSyncAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=39,
)

DESCRIPTOR.message_types_by_name['RspSyncAck'] = _RSPSYNCACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspSyncAck = _reflection.GeneratedProtocolMessageType('RspSyncAck', (_message.Message,), {
  'DESCRIPTOR' : _RSPSYNCACK,
  '__module__' : 'RspSyncAck_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspSyncAck)
  })
_sym_db.RegisterMessage(RspSyncAck)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
