# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RspUpdateMss.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RspUpdateMss.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x12RspUpdateMss.proto\x12\x05\x62link\"\x1a\n\x0cRspUpdateMss\x12\n\n\x02ts\x18\x01 \x01(\x03\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_RSPUPDATEMSS = _descriptor.Descriptor(
  name='RspUpdateMss',
  full_name='blink.RspUpdateMss',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ts', full_name='blink.RspUpdateMss.ts', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=55,
)

DESCRIPTOR.message_types_by_name['RspUpdateMss'] = _RSPUPDATEMSS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RspUpdateMss = _reflection.GeneratedProtocolMessageType('RspUpdateMss', (_message.Message,), {
  'DESCRIPTOR' : _RSPUPDATEMSS,
  '__module__' : 'RspUpdateMss_pb2'
  # @@protoc_insertion_point(class_scope:blink.RspUpdateMss)
  })
_sym_db.RegisterMessage(RspUpdateMss)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
