# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SCallType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SCallType.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x0fSCallType.proto\x12\x05\x62link*>\n\tSCallType\x12\x17\n\x13\x45N_MSG_TYPE_REQUEST\x10\x01\x12\x18\n\x14\x45N_MSG_TYPE_RESPONSE\x10\x02\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_SCALLTYPE = _descriptor.EnumDescriptor(
  name='SCallType',
  full_name='blink.SCallType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EN_MSG_TYPE_REQUEST', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EN_MSG_TYPE_RESPONSE', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=26,
  serialized_end=88,
)
_sym_db.RegisterEnumDescriptor(_SCALLTYPE)

SCallType = enum_type_wrapper.EnumTypeWrapper(_SCALLTYPE)
EN_MSG_TYPE_REQUEST = 1
EN_MSG_TYPE_RESPONSE = 2


DESCRIPTOR.enum_types_by_name['SCallType'] = _SCALLTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
