# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SwooleHead.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SwooleHead.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10SwooleHead.proto\x12\x05\x62link\"\x1a\n\nSwooleHead\x12\x0c\n\x04Host\x18\x01 \x01(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_SWOOLEHEAD = _descriptor.Descriptor(
  name='SwooleHead',
  full_name='blink.SwooleHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Host', full_name='blink.SwooleHead.Host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=53,
)

DESCRIPTOR.message_types_by_name['SwooleHead'] = _SWOOLEHEAD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SwooleHead = _reflection.GeneratedProtocolMessageType('SwooleHead', (_message.Message,), {
  'DESCRIPTOR' : _SWOOLEHEAD,
  '__module__' : 'SwooleHead_pb2'
  # @@protoc_insertion_point(class_scope:blink.SwooleHead)
  })
_sym_db.RegisterMessage(SwooleHead)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
