# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TracePoint.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='TracePoint.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10TracePoint.proto\x12\x05\x62link\"\xd2\x01\n\nTracePoint\x12\x13\n\x0b\x63\x61ller_cost\x18\t \x01(\x05\x12\x15\n\rcaller_rcv_ts\x18\x08 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x10\n\x08\x65rr_code\x18\x07 \x01(\x05\x12\n\n\x02ip\x18\x06 \x01(\t\x12\x0e\n\x06method\x18\x03 \x01(\t\x12\x12\n\nmilli_cost\x18\x05 \x01(\x05\x12!\n\x06points\x18\n \x03(\x0b\x32\x11.blink.TracePoint\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_TRACEPOINT = _descriptor.Descriptor(
  name='TracePoint',
  full_name='blink.TracePoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='caller_cost', full_name='blink.TracePoint.caller_cost', index=0,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='caller_rcv_ts', full_name='blink.TracePoint.caller_rcv_ts', index=1,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='blink.TracePoint.content', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='blink.TracePoint.err_code', index=3,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='blink.TracePoint.ip', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='blink.TracePoint.method', index=5,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='milli_cost', full_name='blink.TracePoint.milli_cost', index=6,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='points', full_name='blink.TracePoint.points', index=7,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='blink.TracePoint.service', index=8,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='blink.TracePoint.timestamp', index=9,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=238,
)

_TRACEPOINT.fields_by_name['points'].message_type = _TRACEPOINT
DESCRIPTOR.message_types_by_name['TracePoint'] = _TRACEPOINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TracePoint = _reflection.GeneratedProtocolMessageType('TracePoint', (_message.Message,), {
  'DESCRIPTOR' : _TRACEPOINT,
  '__module__' : 'TracePoint_pb2'
  # @@protoc_insertion_point(class_scope:blink.TracePoint)
  })
_sym_db.RegisterMessage(TracePoint)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
