# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UidCodeMsg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UidCodeMsg.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x10UidCodeMsg.proto\x12\x05\x62link\"<\n\nUidCodeMsg\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\x12\x0f\n\x07\x65rr_msg\x18\x03 \x01(\t\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)




_UIDCODEMSG = _descriptor.Descriptor(
  name='UidCodeMsg',
  full_name='blink.UidCodeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='blink.UidCodeMsg.err_code', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='blink.UidCodeMsg.err_msg', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.UidCodeMsg.uid', index=2,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['UidCodeMsg'] = _UIDCODEMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UidCodeMsg = _reflection.GeneratedProtocolMessageType('UidCodeMsg', (_message.Message,), {
  'DESCRIPTOR' : _UIDCODEMSG,
  '__module__' : 'UidCodeMsg_pb2'
  # @@protoc_insertion_point(class_scope:blink.UidCodeMsg)
  })
_sym_db.RegisterMessage(UidCodeMsg)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
