# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserPlatformEnum.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserPlatformEnum.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x16UserPlatformEnum.proto\x12\x05\x62link*[\n\x10UserPlatformEnum\x12\x15\n\x11USER_PLATFORM_IOS\x10\x00\x12\x19\n\x15USER_PLATFORM_ANDROID\x10\x01\x12\x15\n\x11USER_PLATFORM_WEB\x10\x02\x42 \n\x1e\x63om.bilibili.bplus.im.protobuf'
)

_USERPLATFORMENUM = _descriptor.EnumDescriptor(
  name='UserPlatformEnum',
  full_name='blink.UserPlatformEnum',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='USER_PLATFORM_IOS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_PLATFORM_ANDROID', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER_PLATFORM_WEB', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=33,
  serialized_end=124,
)
_sym_db.RegisterEnumDescriptor(_USERPLATFORMENUM)

UserPlatformEnum = enum_type_wrapper.EnumTypeWrapper(_USERPLATFORMENUM)
USER_PLATFORM_IOS = 0
USER_PLATFORM_ANDROID = 1
USER_PLATFORM_WEB = 2


DESCRIPTOR.enum_types_by_name['UserPlatformEnum'] = _USERPLATFORMENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
