# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: UserProfileContext.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import UserPlatformEnum_pb2 as UserPlatformEnum__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='UserProfileContext.proto',
  package='blink',
  syntax='proto2',
  serialized_options=b'\n\036com.bilibili.bplus.im.protobuf',
  serialized_pb=b'\n\x18UserProfileContext.proto\x12\x05\x62link\x1a\x16UserPlatformEnum.proto\"\x85\x01\n\x12UserProfileContext\x12\x13\n\x0b\x62ody_header\x18\x04 \x02(\t\x12\x11\n\tbody_http\x18\x05 \x02(\t\x12)\n\x08platform\x18\x03 \x02(\x0e\x32\x17.blink.UserPlatformEnum\x12\x0b\n\x03uid\x18\x01 \x02(\x04\x12\x0f\n\x07user_ip\x18\x02 \x02(\tB \n\x1e\x63om.bilibili.bplus.im.protobuf'
  ,
  dependencies=[UserPlatformEnum__pb2.DESCRIPTOR,])




_USERPROFILECONTEXT = _descriptor.Descriptor(
  name='UserProfileContext',
  full_name='blink.UserProfileContext',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body_header', full_name='blink.UserProfileContext.body_header', index=0,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body_http', full_name='blink.UserProfileContext.body_http', index=1,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='platform', full_name='blink.UserProfileContext.platform', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='blink.UserProfileContext.uid', index=3,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_ip', full_name='blink.UserProfileContext.user_ip', index=4,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=193,
)

_USERPROFILECONTEXT.fields_by_name['platform'].enum_type = UserPlatformEnum__pb2._USERPLATFORMENUM
DESCRIPTOR.message_types_by_name['UserProfileContext'] = _USERPROFILECONTEXT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserProfileContext = _reflection.GeneratedProtocolMessageType('UserProfileContext', (_message.Message,), {
  'DESCRIPTOR' : _USERPROFILECONTEXT,
  '__module__' : 'UserProfileContext_pb2'
  # @@protoc_insertion_point(class_scope:blink.UserProfileContext)
  })
_sym_db.RegisterMessage(UserProfileContext)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
